version: "3.9"

services:

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  mongo:
    image: mongo:6
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  qdrant:
    image: qdrant/qdrant:v1.8.1
    ports:
      - 6333:6333
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  mongodb_data_container:
  qdrant_storage: